homepage: "https://pypi.org/project/xmltodict/"
language: python
primary_contact: "martinblech@gmail.com"
auto_ccs: 
  - "ennamarie19@gmail.com"
fuzzing_engines: 
  - libfuzzer
sanitizers: 
  - address
  - undefined
main_repo: "https://github.com/martinblech/xmltodict.git"
